import { Timestamp } from 'firebase/firestore';
// Import the Address interface we defined earlier
import { Address } from './candidate'; // Adjust path if you move Address later
// Import the UserRole enum defined in user.ts
import { UserRole } from './user'; // Adjust path if needed

/**
 * Represents the status of a company account on the platform.
 */
export enum CompanyStatus {
  ACTIVE = 'Active',
  SUSPENDED = 'Suspended',
  PENDING_APPROVAL = 'PendingApproval',
}

/**
 * Represents a specific branch or location associated with a CompanyProfile.
 */
interface CompanyBranch {
  id: string; // Unique identifier for this branch (e.g., auto-generated ID)
  branchName: string; // Name of the branch (e.g., "Pretoria East Branch", "Head Office")
  address: Address; // Physical address of the branch
  contactNumber?: string; // Optional: Specific phone number for this branch
  contactEmail?: string; // Optional: Specific email address for this branch
  isHeadOffice?: boolean; // Optional: Flag to indicate if this is the main HQ
  // Add other branch-specific fields if needed (e.g., managerId, operational hours)
}

/**
 * Represents a user who is a member of a company's team on the Identiq platform.
 * This defines their relationship to the company and their roles within it.
 * This might be stored in a subcollection under the company or a separate top-level collection.
 */
interface TeamMember {
  userId: string; // The User ID (links to the main 'users' collection document)
  // companyId: string; // Often implied if stored as subcollection, needed if stored separately
  roles: UserRole[]; // Array of roles this user has *within this company*.
                      // Primarily uses roles like COMPANY_ADMIN, COMPANY_USER.
  addedAt: Timestamp; // When this member was added to the company team
  isActive?: boolean; // Flag to enable/disable this member's access to this company's data
  branchId?: string; // Optional: ID of the CompanyBranch this member is associated with
  // Add other relevant fields like jobTitle?
}

// Placeholder for SocialMediaLinks
interface SocialMediaLinks {
    linkedIn?: string;
    facebook?: string;
    instagram?: string;
    twitter?: string;
    // Add other platforms if needed
}

/**
 * Represents the core profile data for a Company using the Identiq platform.
 * This would likely correspond to documents in a 'companies' collection in Firestore.
 */
export interface ContactPerson {
  name: string; // Encrypted
  email: string; // Encrypted
  phone?: string; // Encrypted
  position?: string;
}

export interface CompanyProfile {
  id: string; // Unique ID for this company document (can be auto-generated by Firestore)
  companyId?: string; // Encrypted // Matches auth UID for company admin or custom ID
  name: string; // Official company name
  // registrationNumber?: string; // Optional: Keeping cipcNumber as the primary SA identifier
  cipcNumber?: string; // South African CIPC number
  psiraNumber?: string; // Company's PSIRA registration number
  companySize?: string; // e.g., '1-10', '11-50', '51-200', '200+'
  specialistFields?: string[]; // Array of strings listing specializations
  companyDescription?: string; // ADDED: Optional company bio/description

  // Contact details (Visibility controlled by Security Rules/UI)
  address: Address; // Encrypted (Fields within Address marked)
  contactNumber: string; // Primary phone number
  contactEmail: string; // Primary contact email

  website?: string; // Optional company website URL
  logoUrl?: string; // Optional URL for the company logo
  socialMediaLinks?: SocialMediaLinks; // ADDED: Optional social media links

  status: CompanyStatus; // Account status (Active, Suspended, etc.)
  createdAt: Timestamp; // When the company record was created
  updatedAt: Timestamp; // When the company record was last updated

  // Billing Related Fields
  billingPlan?: 'Monthly' | 'Yearly';
  financeEmail?: string; // Dedicated email for finance/billing comms

  // Branch Management
  branches?: CompanyBranch[]; // Array to hold branch information (now defined)

  // Identiq Admin Assigned (Optional)
  assignedRepresentativeId?: string; // User ID of the Identiq admin assigned

  // Recruitment Cycle Data (Self-reported / Admin maintained)
  hiresLastYear?: number; // ADDED: Optional number for baseline/demo

  primaryContact: ContactPerson; // Encrypted (Fields within ContactPerson marked)
  billingContact?: ContactPerson; // Encrypted (Fields within ContactPerson marked)
  vatNumber?: string; // Encrypted
  registrationNumber?: string; // Encrypted
}

export interface CompanyUser {
  userId: string; // Encrypted // Matches the auth UID of the user
  companyId: string; // Encrypted // ID of the company they belong to
  email: string; // Encrypted // Denormalized for display/rules? Or get from User?
  name: string; // Encrypted // Denormalized for display
  phone?: string; // Encrypted
  role: 'Admin' | 'HiringManager' | 'TeamMember' | 'Billing'; // Permissions role
  status: 'Active' | 'Invited' | 'Suspended';
  invitedAt?: Timestamp;
  joinedAt?: Timestamp;
  lastLogin?: Timestamp;
}